# Generated by Django 6.0.1 on 2026-02-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_userprofile_default_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.location'),
            preserve_default=False,
        ),
    ]
