# Generated by Django 6.0.1 on 2026-02-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_purchaseorder_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='default_location',
        ),
    ]
