# Generated by Django 6.0.1 on 2026-02-10 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_location_userprofile_default_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['item'], name='inventory_s_item_id_646ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['location'], name='inventory_s_locatio_28ffea_idx'),
        ),
    ]
