# Generated by Django 6.0.1 on 2026-02-12 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supplier_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='location',
            new_name='inventory_l_owner_i_7df33d_idx',
            old_name='inventory_l_owner_i_0bb2f8_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='inventory_l_name_93296b_idx',
            old_name='inventory_l_name_i_2b0f4a_idx',
        ),
        migrations.AddField(
            model_name='sale',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['owner'], name='inventory_s_owner_i_86be4d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['receipt_no'], name='inventory_s_receipt_49061b_idx'),
        ),
    ]
