# Generated by Codex on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_location_owner_alter_sale_cashier"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="country_code",
            field=models.CharField(
                choices=[("JM", "Jamaica"), ("TT", "Trinidad & Tobago"), ("BB", "Barbados")],
                default="JM",
                max_length=2,
            ),
        ),
    ]
