# Generated by Django 6.0.1 on 2026-02-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_location_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(choices=[('JM', 'Jamaica'), ('TT', 'Trinidad & Tobago'), ('BB', 'Barbados'), ('GY', 'Guyana'), ('LC', 'Saint Lucia'), ('INT', 'International')], default='JM', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='inventory.location'),
        ),
    ]
