# Generated by Django 6.0.1 on 2026-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_location_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
