# Generated by Django 5.2.4 on 2026-02-22 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parent_admin',
            field=models.ForeignKey(blank=True, help_text='The Admin account this staff member belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='inventory.userprofile'),
        ),
    ]
