# Generated by Django 5.2.4 on 2026-02-22 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_userprofile_parent_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('owner', 'sku')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['owner', 'sku'], name='inventory_owner_sku_idx'),
        ),
    ]
