# Generated by Django 5.2.4 on 2026-02-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_item_sku_alter_item_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='inventory_u_role_72f4b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='inventory_u_plan_0278ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='inventory_u_status_idx',
        ),
    ]
