# Generated by Django 5.2.4 on 2026-02-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receipt_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
