# Generated by Django 5.2.4 on 2026-02-28 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_item_supplier_item_inventory_i_supplier_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('owner', 'sku')},
        ),
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('owner', 'barcode'), ('owner', 'sku')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['owner', 'barcode'], name='inventory_owner_barcode_idx'),
        ),
    ]
