# Generated by Django 5.2.4 on 2026-02-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_item_unique_together_item_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tender',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('jamdex', 'JAM-DEX'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
