# Generated by Django 5.2.4 on 2026-02-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_sale_tender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tender',
            field=models.CharField(choices=[('cash', 'Cash'), ('jamdex', 'JAM-DEX')], default='cash', max_length=20),
        ),
    ]
