# Generated by Django 5.2.4 on 2026-03-22 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_sale_tender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location/Branch'},
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='inventory_l_owner_idx',
            old_name='inventory_l_owner_i_7df33d_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='inventory_l_name_idx',
            old_name='inventory_l_name_93296b_idx',
        ),
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('user', 'parent_admin')},
        ),
        migrations.AddField(
            model_name='cashshift',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='inventory.cashshift'),
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['is_closed', 'cashier'], name='inventory_c_is_clos_ae8480_idx'),
        ),
    ]
