# Generated by Django 5.2.4 on 2026-03-22 11:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_remove_cashshift_inventory_c_is_clos_ae8480_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='inventory_i_categor_dcc1fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='inventory_i_supplier_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='inv_item_name_idx',
            old_name='inventory_i_name_637656_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='inv_owner_sku_idx',
            old_name='inventory_owner_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='inv_owner_barcode_idx',
            old_name='inventory_owner_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sale_timestamp_idx',
            old_name='inventory_s_timesta_fc4738_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sale_cashier_idx',
            old_name='inventory_s_cashier_ebef02_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sale_location_idx',
            old_name='inventory_s_locatio_52b78a_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sale_owner_idx',
            old_name='inventory_s_owner_i_86be4d_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sale_receipt_idx',
            old_name='inventory_s_receipt_49061b_idx',
        ),
        migrations.AddField(
            model_name='item',
            name='is_taxable',
            field=models.BooleanField(default=True, help_text='Uncheck for GCT Exempt/Zero-rated items (e.g., basic food items, medicine).'),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total price minus GCT', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total GCT collected for this line', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit (GCT Inclusive) at time of sale', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Shelf price (GCT Inclusive)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='gct_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tender',
            field=models.CharField(choices=[('cash', 'Cash'), ('jamdex', 'JAM-DEX'), ('card', 'Debit/Credit')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Final price (Quantity * Unit Price)', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='inv_item_status_idx'),
        ),
    ]
