# Generated by Django 5.2.4 on 2026-04-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_saleitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashshift',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
