# Generated by Django 5.2.4 on 2026-04-06 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_cashshift_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashshift',
            name='opened_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
