# Generated by Django 5.2.4 on 2026-05-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_salesinvoicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashshift',
            name='last_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_non_negative'),
        ),
    ]
