# Generated by Django 5.2.4 on 2026-05-13 23:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_cashshift_last_calculated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='conflicts_detected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='conflicts_resolved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='direction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='items_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='items_pulled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='items_pushed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='sync_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='sync_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sync_source',
            field=models.CharField(default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='sync_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sync_source',
            field=models.CharField(default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='sync_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
