# Generated by Django 5.2.4 on 2026-05-14 00:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_auditlog_completed_at_auditlog_conflicts_detected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
