# Generated by Django 5.2.4 on 2026-05-23 16:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_auditlog_sync_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashshift',
            options={'ordering': ['-opened_at']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location/Branch', 'verbose_name_plural': 'Locations/Branches'},
        ),
        migrations.AlterModelOptions(
            name='stockrecord',
            options={'verbose_name': 'Stock Record', 'verbose_name_plural': 'Stock Records'},
        ),
        migrations.RemoveConstraint(
            model_name='stockrecord',
            name='stock_non_negative',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='inv_item_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='inv_item_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='inventory_l_owner_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockrecord',
            name='inventory_s_item_id_646ab0_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockrecord',
            name='inventory_s_locatio_28ffea_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cashshift',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='brand',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_rate_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='The exact GCT percentage applied at the moment of checkout (e.g., 15.00).', max_digits=5),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='last_restocked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert point for low inventory notifications at this branch.'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='The exact timestamp when the shift session was finalized and closed.', null=True),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='opened_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='The exact timestamp when the cashier opened the shift and drawer session.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft'), ('out_of_stock', 'Out of Stock')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Final gross price (Quantity * Unit Price)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='The actual physical inventory count at this specific branch location.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='parent_admin',
            field=models.ForeignKey(blank=True, help_text='The Admin account profile this staff member belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='inventory.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['owner', 'name'], name='inv_owner_item_name_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['owner', 'status'], name='inv_owner_item_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shift', 'tender'], name='sale_shift_tender_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['item', 'location'], name='stock_item_loc_idx'),
        ),
    ]
