# Generated by Django 5.2.4 on 2026-06-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_alter_userverification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_daily_summary',
            field=models.BooleanField(default=False, help_text='Allows a manager to edit Daily Summary comments when granted by an admin.'),
        ),
    ]
