# Generated by Codex on 2026-06-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0046_userprofile_can_edit_daily_summary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCashCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary_date", models.DateField(db_index=True)),
                ("qty_5000", models.PositiveIntegerField(default=0)),
                ("qty_2000", models.PositiveIntegerField(default=0)),
                ("qty_1000", models.PositiveIntegerField(default=0)),
                ("qty_500", models.PositiveIntegerField(default=0)),
                ("qty_100", models.PositiveIntegerField(default=0)),
                ("qty_50", models.PositiveIntegerField(default=0)),
                ("qty_20", models.PositiveIntegerField(default=0)),
                ("qty_10", models.PositiveIntegerField(default=0)),
                ("qty_5", models.PositiveIntegerField(default=0)),
                ("qty_1", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_cash_counts", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "updated_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_daily_cash_counts", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-summary_date"],
                "indexes": [models.Index(fields=["owner", "summary_date"], name="daily_cash_owner_date_idx")],
                "constraints": [models.UniqueConstraint(fields=["owner", "summary_date"], name="uniq_daily_cash_count_owner_date")],
            },
        ),
    ]
