# Generated by Django 5.2.4 on 2026-06-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_dailycashcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoicepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('card', 'Card (Legacy)'), ('jamdex', 'JAM-DEX'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit_daily_summary',
            field=models.BooleanField(default=False, help_text='Allows a manager or cashier to use Daily Summary when granted by an admin or superuser.'),
        ),
    ]
