# Generated by Codex on 2026-06-28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0048_alter_salesinvoicepayment_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycashcount",
            name="bns_machine_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="dailycashcount",
            name="ncb_machine_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
    ]
