# Generated by Django 5.2.4 on 2026-07-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_sale_amount_paid_change_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoicepayment',
            name='payment_method',
            field=models.CharField(choices=[('account_credit', 'Account Credit'), ('cash', 'Cash'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('card', 'Card (Legacy)'), ('jamdex', 'JAM-DEX'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
