# Generated by Django 5.2.4 on 2026-07-09 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_salesinvoicecreditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.location'),
        ),
    ]
