# Generated by Django 5.2.4 on 2026-07-13 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_purchaseorder_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='email_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='last_emailed_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sale',
            name='last_emailed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailed_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sale',
            name='previous_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_revisions', to='inventory.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='printed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='revision_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('revised', 'Revised'), ('emailed', 'Emailed'), ('voided', 'Voided')], db_index=True, default='finalized', max_length=16),
        ),
        migrations.AddField(
            model_name='sale',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['receipt_status'], name='sale_receipt_status_idx'),
        ),
        migrations.AddField(
            model_name='receiptemaillog',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_email_logs', to='inventory.sale'),
        ),
        migrations.AddField(
            model_name='receiptemaillog',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_email_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptrevision',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptrevision',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_revisions', to='inventory.sale'),
        ),
        migrations.AddIndex(
            model_name='receiptemaillog',
            index=models.Index(fields=['sale', 'status'], name='receipt_email_sale_status_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptemaillog',
            index=models.Index(fields=['sent_at'], name='receipt_email_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptrevision',
            index=models.Index(fields=['sale', 'revision_number'], name='receipt_rev_sale_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptrevision',
            index=models.Index(fields=['created_at'], name='receipt_rev_created_idx'),
        ),
    ]
