# Generated by Django 5.2.4 on 2026-07-14 00:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_receiptemaillog_receiptrevision_sale_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycashcount',
            name='cash_expenditure_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='dailycashcount',
            name='cash_expenditure_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailycashcount',
            name='cash_lodgement_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='dailycashcount',
            name='cash_lodgement_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailycashcount',
            name='opening_cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
