# Generated by Django 5.2.4 on 2026-07-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_dailycashcount_cash_expenditure_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycashcount',
            name='cash_expenditure_currency',
            field=models.CharField(choices=[('JMD', 'JMD'), ('USD', 'USD')], default='JMD', max_length=3),
        ),
        migrations.AddField(
            model_name='dailycashcount',
            name='cash_expenditure_party_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailycashcount',
            name='cash_expenditure_receipt_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
