# Generated by Django 5.2.4 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0059_dailycashcount_cash_expenditure_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="country_code",
            field=models.CharField(
                choices=[
                    ("JM", "Jamaica"),
                    ("TT", "Trinidad & Tobago"),
                    ("BB", "Barbados"),
                    ("GY", "Guyana"),
                    ("LC", "Saint Lucia"),
                    ("INT", "International"),
                ],
                default="JM",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="supplier_type",
            field=models.CharField(
                choices=[
                    ("local", "Local supplier"),
                    ("international", "International supplier"),
                ],
                db_index=True,
                default="local",
                max_length=20,
            ),
        ),
    ]
