# Generated by Django 5.2.4 on 2026-07-24 00:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_financial_ledger_cutover(apps, schema_editor):
    SalesInvoice = apps.get_model("inventory", "SalesInvoice")
    SalesInvoicePayment = apps.get_model("inventory", "SalesInvoicePayment")
    Customer = apps.get_model("inventory", "Customer")
    CustomerCreditMovement = apps.get_model("inventory", "CustomerCreditMovement")

    legacy_payments = []
    for invoice in SalesInvoice.objects.filter(status="paid").iterator():
        if SalesInvoicePayment.objects.filter(invoice_id=invoice.id).exists():
            continue
        credit_total = (
            invoice.credit_notes.aggregate(total=models.Sum("amount"))["total"]
            or Decimal("0.00")
        )
        effective_total = max(
            Decimal(invoice.total_amount or "0.00") - Decimal(credit_total),
            Decimal("0.00"),
        ).quantize(Decimal("0.01"))
        if effective_total <= Decimal("0.00"):
            continue
        legacy_payments.append(
            SalesInvoicePayment(
                invoice_id=invoice.id,
                owner_id=invoice.owner_id,
                customer_id=invoice.customer_id,
                location_id=invoice.location_id,
                received_by_id=invoice.created_by_id,
                amount=effective_total,
                payment_method="other",
                notes="QS-003 legacy paid-status ledger backfill.",
                payment_date=invoice.issued_at,
            )
        )
    if legacy_payments:
        SalesInvoicePayment.objects.bulk_create(legacy_payments)

    payments_to_update = []
    for payment in SalesInvoicePayment.objects.select_related("invoice").all().iterator():
        payment.owner_id = payment.invoice.owner_id
        payment.customer_id = payment.invoice.customer_id
        payment.location_id = payment.invoice.location_id
        payments_to_update.append(payment)
    if payments_to_update:
        SalesInvoicePayment.objects.bulk_update(
            payments_to_update,
            ["owner", "customer", "location"],
        )

    cutover_time = timezone.now()
    opening_movements = [
        CustomerCreditMovement(
            customer_id=customer.id,
            amount=customer.credit_balance,
            movement_type="opening_balance",
            reason="QS-003 opening balance at customer-credit ledger cutover.",
            created_at=cutover_time,
        )
        for customer in Customer.objects.exclude(credit_balance=Decimal("0.00")).iterator()
    ]
    if opening_movements:
        CustomerCreditMovement.objects.bulk_create(opening_movements)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_sales_invoice_payment_integrity_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('movement_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('manual_adjustment', 'Manual Adjustment'), ('invoice_overpayment', 'Invoice Overpayment'), ('invoice_credit_application', 'Invoice Credit Application'), ('invoice_credit_note', 'Invoice Credit Note'), ('payment_reversal', 'Payment Reversal'), ('pos_credit_application', 'POS Credit Application'), ('pos_overpayment', 'POS Overpayment')], max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoicePaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversed_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='salesinvoicepayment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_payment_ledger', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='salesinvoicepayment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_payment_ledger', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='salesinvoicepayment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_payment_ledger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoicecreditnote',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='inventory.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='salesinvoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.salesinvoice'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicepayment',
            index=models.Index(fields=['owner', 'payment_date'], name='sales_pay_owner_date_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicepayment',
            index=models.Index(fields=['location', 'payment_date'], name='sales_pay_loc_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('credit_balance__gte', Decimal('0.00'))), name='customer_credit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoicecreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='sales_credit_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoicecreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('credited_customer_amount__gte', Decimal('0.00'))), name='sales_credit_customer_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoicecreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('credited_customer_amount__lte', models.F('amount'))), name='sales_credit_customer_lte_amount'),
        ),
        migrations.AddField(
            model_name='customercreditmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_credit_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercreditmovement',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_credit_movements', to='inventory.salesinvoicecreditnote'),
        ),
        migrations.AddField(
            model_name='customercreditmovement',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_movements', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='customercreditmovement',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_credit_movements', to='inventory.salesinvoicepayment'),
        ),
        migrations.AddField(
            model_name='customercreditmovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_credit_movements', to='inventory.sale'),
        ),
        migrations.AddField(
            model_name='salesinvoicepaymentreversal',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='inventory.salesinvoicepayment'),
        ),
        migrations.AddField(
            model_name='salesinvoicepaymentreversal',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_payment_reversals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercreditmovement',
            name='payment_reversal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_credit_movements', to='inventory.salesinvoicepaymentreversal'),
        ),
        migrations.RunPython(
            backfill_financial_ledger_cutover,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='salesinvoicepaymentreversal',
            index=models.Index(fields=['created_at'], name='sales_rev_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoicepaymentreversal',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='sales_rev_reason_required'),
        ),
        migrations.AddIndex(
            model_name='customercreditmovement',
            index=models.Index(fields=['customer', 'created_at'], name='cust_credit_ledger_idx'),
        ),
        migrations.AddIndex(
            model_name='customercreditmovement',
            index=models.Index(fields=['movement_type'], name='cust_credit_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercreditmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount', Decimal('0.00')), _negated=True), name='cust_credit_move_nonzero'),
        ),
    ]
