# Generated by Django 5.2.4 on 2026-07-24 00:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_supplier_financial_ledger(apps, schema_editor):
    SupplierInvoice = apps.get_model("inventory", "SupplierInvoice")
    SupplierInvoicePayment = apps.get_model("inventory", "SupplierInvoicePayment")
    SupplierInvoiceAdjustment = apps.get_model("inventory", "SupplierInvoiceAdjustment")

    invoices = SupplierInvoice.objects.select_related("supplier", "voided_by").all()
    for invoice in invoices.iterator():
        amount = Decimal(invoice.amount or "0.00").quantize(Decimal("0.01"))
        paid_amount = Decimal(invoice.paid_amount or "0.00").quantize(Decimal("0.01"))
        if paid_amount < Decimal("0.00"):
            raise RuntimeError(
                f"Supplier invoice {invoice.pk} has a negative paid_amount and cannot be backfilled safely."
            )
        if amount <= Decimal("0.00") and (paid_amount > Decimal("0.00") or invoice.status == "Void"):
            raise RuntimeError(
                f"Supplier invoice {invoice.pk} has non-positive value with financial history."
            )

        if paid_amount > Decimal("0.00"):
            SupplierInvoicePayment.objects.create(
                invoice_id=invoice.pk,
                owner_id=invoice.supplier.owner_id,
                supplier_id=invoice.supplier_id,
                location_id=invoice.location_id,
                paid_by_id=None,
                paid_by_username="",
                amount=paid_amount,
                reference=f"LEGACY-{invoice.pk}",
                notes="Synthetic payment created from the legacy paid_amount cache during QS-003 backfill.",
                payment_date=invoice.created_at,
            )

        if invoice.status == "Void":
            adjustment = SupplierInvoiceAdjustment.objects.create(
                invoice_id=invoice.pk,
                owner_id=invoice.supplier.owner_id,
                supplier_id=invoice.supplier_id,
                location_id=invoice.location_id,
                adjustment_type="void_credit",
                amount=amount,
                reason=invoice.void_reason or "Historical void backfilled during QS-003.",
                created_by_id=invoice.voided_by_id,
                created_by_username=(
                    invoice.voided_by.username
                    if invoice.voided_by_id
                    else ""
                ),
            )
            SupplierInvoiceAdjustment.objects.filter(pk=adjustment.pk).update(
                created_at=invoice.voided_at or invoice.created_at,
            )
        else:
            reconciled_status = "Paid" if paid_amount >= amount else "Pending"
            if invoice.status != reconciled_status:
                SupplierInvoice.objects.filter(pk=invoice.pk).update(status=reconciled_status)


def restore_supplier_payment_cache(apps, schema_editor):
    from django.db.models import Sum

    SupplierInvoice = apps.get_model("inventory", "SupplierInvoice")
    SupplierInvoicePayment = apps.get_model("inventory", "SupplierInvoicePayment")
    SupplierInvoiceAdjustment = apps.get_model("inventory", "SupplierInvoiceAdjustment")

    for invoice in SupplierInvoice.objects.all().iterator():
        paid_amount = (
            SupplierInvoicePayment.objects.filter(
                invoice_id=invoice.pk,
                reversal__isnull=True,
            ).aggregate(total=Sum("amount"))["total"]
            or Decimal("0.00")
        )
        is_void = SupplierInvoiceAdjustment.objects.filter(
            invoice_id=invoice.pk,
            adjustment_type="void_credit",
        ).exists()
        status = "Void" if is_void else ("Paid" if paid_amount >= invoice.amount else "Pending")
        SupplierInvoice.objects.filter(pk=invoice.pk).update(
            paid_amount=paid_amount,
            status=status,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_sales_invoice_payment_owner_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.supplierinvoice')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_payment_ledger', to='inventory.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_payment_ledger', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_ledger', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoicePaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversed_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='inventory.supplierinvoicepayment')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_payment_reversals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('void_credit', 'Void Credit')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('created_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.supplierinvoice')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_adjustment_ledger', to='inventory.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_adjustment_ledger', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_adjustment_ledger', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['invoice'], name='supplier_adj_invoice_idx'), models.Index(fields=['owner', 'created_at'], name='supplier_adj_owner_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='supplier_adj_amount_positive'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='supplier_adj_reason_required'), models.UniqueConstraint(fields=('invoice', 'adjustment_type'), name='supplier_adj_invoice_type_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='supplierinvoicepayment',
            index=models.Index(fields=['invoice'], name='supplier_pay_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoicepayment',
            index=models.Index(fields=['owner', 'payment_date'], name='supplier_pay_owner_date_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoicepayment',
            index=models.Index(fields=['supplier', 'payment_date'], name='supplier_pay_vendor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoicepayment',
            index=models.Index(fields=['location', 'payment_date'], name='supplier_pay_loc_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoicepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='supplier_pay_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoicepaymentreversal',
            index=models.Index(fields=['created_at'], name='supplier_rev_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoicepaymentreversal',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='supplier_rev_reason_required'),
        ),
        migrations.RunPython(
            backfill_supplier_financial_ledger,
            restore_supplier_payment_cache,
        ),
    ]
