# Generated by Django 5.2.4 on 2026-07-24 00:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_actor_snapshots(apps, schema_editor):
    SalesInvoicePayment = apps.get_model("inventory", "SalesInvoicePayment")
    SalesInvoiceCreditNote = apps.get_model("inventory", "SalesInvoiceCreditNote")
    CustomerCreditMovement = apps.get_model("inventory", "CustomerCreditMovement")
    User = apps.get_model("auth", "User")

    usernames = dict(User.objects.values_list("id", "username"))
    for model, actor_field, snapshot_field in (
        (SalesInvoicePayment, "received_by_id", "received_by_username"),
        (SalesInvoiceCreditNote, "created_by_id", "created_by_username"),
        (CustomerCreditMovement, "created_by_id", "created_by_username"),
    ):
        rows = list(model.objects.filter(**{f"{snapshot_field}__exact": ""}).iterator())
        for row in rows:
            username = usernames.get(getattr(row, actor_field), "")
            if username:
                setattr(row, snapshot_field, username)
        if rows:
            model.objects.bulk_update(rows, [snapshot_field])


def noop_reverse(apps, schema_editor):
    # Actor snapshots are retained as durable evidence and are intentionally not erased.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_alter_purchaseorder_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoiceRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('reason', models.TextField()),
                ('refund_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-refund_date', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='supplierinvoiceadjustment',
            name='supplier_adj_invoice_type_uniq',
        ),
        migrations.AddField(
            model_name='customer',
            name='archive_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='customercreditmovement',
            name='created_by_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='location',
            name='archive_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salesinvoicecreditnote',
            name='created_by_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='salesinvoicepayment',
            name='received_by_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='archive_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='archive_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='supplierinvoiceadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('void_credit', 'Void Credit'), ('supplier_credit', 'Supplier Credit Note')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('adjustment_type', 'void_credit')), fields=('invoice',), name='supplier_adj_invoice_void_uniq'),
        ),
        migrations.AddField(
            model_name='supplierinvoicerefund',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='inventory.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='supplierinvoicerefund',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_refund_ledger', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='supplierinvoicerefund',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_refund_ledger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierinvoicerefund',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_refunds_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierinvoicerefund',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_ledger', to='inventory.supplier'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoicerefund',
            index=models.Index(fields=['invoice'], name='supplier_refund_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoicerefund',
            index=models.Index(fields=['owner', 'refund_date'], name='supplier_refund_owner_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoicerefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='supplier_refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoicerefund',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='supplier_refund_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoicerefund',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('invoice', 'reference'), name='supplier_refund_invoice_reference_uniq'),
        ),
        migrations.RunPython(backfill_actor_snapshots, noop_reverse),
    ]
