# Generated by Django 5.2.4 on 2026-07-24 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_supplierinvoicerefund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptemaillog',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_email_logs', to='inventory.sale'),
        ),
        migrations.AlterField(
            model_name='receiptrevision',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_revisions', to='inventory.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.sale'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='issued', max_length=16),
        ),
    ]
