# Generated by Django 5.2.4 on 2026-07-24 01:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_cash_shift_snapshots(apps, schema_editor):
    CashShift = apps.get_model("inventory", "CashShift")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    Location = apps.get_model("inventory", "Location")

    users = {user.pk: getattr(user, "username", "") or "" for user in User.objects.all()}
    locations = {
        loc.pk: (getattr(loc, "owner_id", None), getattr(loc, "name", "") or "")
        for loc in Location.objects.all()
    }

    for shift in CashShift.objects.all().iterator():
        updates = {}
        if not shift.owner_id and shift.location_id in locations:
            loc_owner_id, _ = locations[shift.location_id]
            if loc_owner_id:
                updates["owner_id"] = loc_owner_id
        if not shift.cashier_username and shift.cashier_id in users:
            updates["cashier_username"] = users[shift.cashier_id]
        if not shift.location_name and shift.location_id in locations:
            _, loc_name = locations[shift.location_id]
            updates["location_name"] = loc_name
        if updates:
            CashShift.objects.filter(pk=shift.pk).update(**updates)



class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_alter_receiptemaillog_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, default='', max_length=100)),
                ('recorded_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('direction', models.CharField(choices=[('in', 'Cash In'), ('out', 'Cash Out')], max_length=3)),
                ('movement_type', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('refund', 'Cash Refund')], default='cash_out', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CashReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, default='', max_length=100)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('denominations', models.JSONField(blank=True, default=dict)),
                ('reconciled_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cashshift',
            name='cashier_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_cash_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoicepayment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments', to='inventory.cashshift'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='inventory.location'),
        ),
        migrations.RunPython(backfill_cash_shift_snapshots, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='salesinvoicepayment',
            index=models.Index(fields=['shift', 'payment_date'], name='sales_pay_shift_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.UniqueConstraint(condition=models.Q(('is_closed', False)), fields=('cashier', 'location'), name='cashshift_one_open_per_operator_location'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.CheckConstraint(condition=models.Q(('opening_cash__gte', Decimal('0.00'))), name='cashshift_opening_cash_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.CheckConstraint(condition=models.Q(('actual_cash__isnull', True), ('actual_cash__gte', Decimal('0.00')), _connector='OR'), name='cashshift_actual_cash_nonnegative'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_cash_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensating_movements', to='inventory.cashmovement'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='inventory.cashshift'),
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_reconciliations', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_cash_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='inventory.cashshift'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['shift', 'direction', 'created_at'], name='cash_move_shift_dir_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['owner', 'created_at'], name='cash_move_owner_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='cash_movement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('owner', 'shift', 'reference'), name='cash_movement_reference_once_per_shift'),
        ),
        migrations.AddIndex(
            model_name='cashreconciliation',
            index=models.Index(fields=['owner', 'created_at'], name='cash_recon_owner_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashreconciliation',
            constraint=models.CheckConstraint(condition=models.Q(('counted_cash__gte', Decimal('0.00'))), name='cash_recon_counted_nonnegative'),
        ),
    ]
