# Generated by Django 5.2.4 on 2026-07-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_location_inventory_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('converted', 'Converted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=16),
        ),
    ]
