# Generated by Django 5.2.4 on 2026-07-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_alter_salesquotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_tax_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='trn',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
