# Generated by Django 5.2.4 on 2026-07-30 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0075_supplierinvoice_terms_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('xero', 'Xero'), ('quickbooks', 'QuickBooks'), ('sage', 'Sage'), ('generic', 'Generic accounting system')], default='xero', max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('configured', 'Configured'), ('active', 'Active'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('external_tenant_id', models.CharField(blank=True, max_length=120)),
                ('sync_sales', models.BooleanField(default=True)),
                ('sync_sales_invoices', models.BooleanField(default=True)),
                ('sync_purchase_invoices', models.BooleanField(default=False)),
                ('sync_inventory_items', models.BooleanField(default=False)),
                ('settings_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('void', 'Void')], default='create', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('synced', 'Synced'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='inventory.accountingintegration')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_sync_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accountingintegration',
            index=models.Index(fields=['owner', 'provider'], name='acct_int_owner_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingintegration',
            index=models.Index(fields=['status'], name='acct_int_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingintegration',
            constraint=models.UniqueConstraint(fields=('owner', 'provider'), name='acct_int_owner_provider_uniq'),
        ),
        migrations.AddIndex(
            model_name='accountingsyncrecord',
            index=models.Index(fields=['owner', 'status'], name='acct_sync_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingsyncrecord',
            index=models.Index(fields=['integration', 'status'], name='acct_sync_int_status_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingsyncrecord',
            index=models.Index(fields=['content_type', 'object_id'], name='acct_sync_object_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingsyncrecord',
            constraint=models.UniqueConstraint(fields=('integration', 'content_type', 'object_id'), name='acct_sync_int_object_uniq'),
        ),
    ]
