# Generated by Codex on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0076_accountingintegration_accountingsyncrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="due_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
